FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source
COPY public ./public
COPY src ./src

# Expose port
EXPOSE 3000

# Build and serve
ENV REACT_APP_API_URL=http://localhost:5000
RUN npm run build

# Use serve to run the built app
RUN npm install -g serve
CMD ["serve", "-s", "build", "-l", "3000"]
